// <auto-generated />
using System;
using CandidatesManagement.Persistence.Sql.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CandidatesManagement.Persistence.Sql.Migrations
{
    [DbContext(typeof(JobCandidatesDbContext))]
    [Migration("20240705084426_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CandidatesManagement.Core.Entities.JobCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GithubProfile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LinkedInProfile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("JobCandidates");
                });

            modelBuilder.Entity("CandidatesManagement.Core.Entities.JobCandidate", b =>
                {
                    b.OwnsOne("CandidatesManagement.Core.ValueObjects.TimeInterval", "TimeInterval", b1 =>
                        {
                            b1.Property<int>("JobCandidateId")
                                .HasColumnType("int");

                            b1.Property<TimeOnly?>("End")
                                .HasColumnType("time")
                                .HasColumnName("IntervalEnd");

                            b1.Property<TimeOnly?>("Start")
                                .HasColumnType("time")
                                .HasColumnName("IntervalStart");

                            b1.HasKey("JobCandidateId");

                            b1.ToTable("JobCandidates");

                            b1.WithOwner()
                                .HasForeignKey("JobCandidateId");
                        });

                    b.Navigation("TimeInterval");
                });
#pragma warning restore 612, 618
        }
    }
}
